# Generated by Django 3.2.3 on 2021-10-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasuremap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigos',
            name='corpo',
            field=models.TextField(max_length=1000),
        ),
    ]
