# Generated by Django 3.2.3 on 2021-10-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasuremap', '0002_alter_artigos_corpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigos',
            name='imagem',
            field=models.FileField(upload_to='imagens/'),
        ),
    ]
