# Generated by Django 3.2.3 on 2021-10-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasuremap', '0003_alter_artigos_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigos',
            name='id',
        ),
        migrations.AlterField(
            model_name='artigos',
            name='titulo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
