# Generated by Django 3.2.3 on 2021-10-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasuremap', '0005_auto_20211026_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigos',
            name='subtitulo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='artigos',
            name='titulo',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
