# Generated by Django 3.2.3 on 2021-10-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasuremap', '0006_auto_20211026_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigos',
            name='imagem',
            field=models.FileField(upload_to='static/imagens'),
        ),
    ]
