c = {'selic': {0: ['/html/body/app-root/div/app-main/main/div/app-consulta-serie-estatisticas/section/div[2]/div[2]/div/div[2]/div[1]/input-ngselect/div/ng-select/div/div/div[2]/input', 'taxas', '/html/body/ng-dropdown-panel/div/div[2]/div/span'],
            1: ['/html/body/app-root/div/app-main/main/div/app-consulta-serie-estatisticas/section/div[2]/div[2]/div/div[2]/div[2]/input-ngselect/div/ng-select/div/div/div[2]/input', 'mensal','/html/body/ng-dropdown-panel/div/div[2]/div/span'],
            2: ['/html/body/app-root/div/app-main/main/div/app-consulta-serie-estatisticas/section/div[2]/div[2]/div/div[2]/div[3]/div[1]/input-ngselect/div/ng-select/div/div/div[2]/input', 'selic', '/html/body/ng-dropdown-panel/div/div[2]/div/span']},
    'ipca': {0: ['/html/body/app-root/div/app-main/main/div/app-consulta-serie-estatisticas/section/div[2]/div[2]/div/div[2]/div[1]/input-ngselect/div/ng-select/div/div/div[2]/input', 'índices', '/html/body/ng-dropdown-panel/div/div[2]/div/span'],
            1: ['/html/body/app-root/div/app-main/main/div/app-consulta-serie-estatisticas/section/div[2]/div[2]/div/div[2]/div[2]/input-ngselect/div/ng-select/div/div/div[2]/input', 'mensal','/html/body/ng-dropdown-panel/div/div[2]/div/span'],
            2: ['/html/body/app-root/div/app-main/main/div/app-consulta-serie-estatisticas/section/div[2]/div[2]/div/div[2]/div[3]/div[1]/input-ngselect/div/ng-select/div/div/div[2]/input', 'ipca', '/html/body/ng-dropdown-panel/div/div[2]/div/span']},
    'igpm': {0: ['/html/body/app-root/div/app-main/main/div/app-consulta-serie-estatisticas/section/div[2]/div[2]/div/div[2]/div[1]/input-ngselect/div/ng-select/div/div/div[2]/input', 'índice', '/html/body/ng-dropdown-panel/div/div[2]/div/span'],
            1: ['/html/body/app-root/div/app-main/main/div/app-consulta-serie-estatisticas/section/div[2]/div[2]/div/div[2]/div[2]/input-ngselect/div/ng-select/div/div/div[2]/input', 'mensal','/html/body/ng-dropdown-panel/div/div[2]/div/span'],
            2: ['/html/body/app-root/div/app-main/main/div/app-consulta-serie-estatisticas/section/div[2]/div[2]/div/div[2]/div[3]/div[1]/input-ngselect/div/ng-select/div/div/div[2]/input', 'igp', '/html/body/ng-dropdown-panel/div/div[2]/div/span']},
    'pib': {0: ['/html/body/app-root/div/app-main/main/div/app-consulta-serie-estatisticas/section/div[2]/div[2]/div/div[2]/div[1]/input-ngselect/div/ng-select/div/div/div[2]/input', 'atividade', '/html/body/ng-dropdown-panel/div/div[2]/div/span'],
            1: ['/html/body/app-root/div/app-main/main/div/app-consulta-serie-estatisticas/section/div[2]/div[2]/div/div[2]/div[2]/input-ngselect/div/ng-select/div/div/div[2]/input', 'anual','/html/body/ng-dropdown-panel/div/div[2]/div/span'],
            2: ['/html/body/app-root/div/app-main/main/div/app-consulta-serie-estatisticas/section/div[2]/div[2]/div/div[2]/div[3]/div[1]/input-ngselect/div/ng-select/div/div/div[2]/input', 'pib total', '/html/body/ng-dropdown-panel/div/div[2]/div/span']}
            }