# Generated by Django 3.2.3 on 2021-10-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='tp_perfil',
            field=models.CharField(default='A', max_length=2),
        ),
    ]
