# Generated by Django 3.2.3 on 2021-11-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_pcredor_liquidez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pamplo',
            name='liquidez',
            field=models.CharField(choices=[('D+1', 'Diária'), ('D+0', 'Imediata'), ('D+30', 'D+30'), ('N', 'Nula'), ('NV', 'No vencimento')], default='D+1', max_length=15),
        ),
        migrations.AlterField(
            model_name='pcredor',
            name='liquidez',
            field=models.CharField(choices=[('D+1', 'Diária'), ('D+0', 'Imediata'), ('D+30', 'D+30'), ('N', 'Nula'), ('NV', 'No vencimento')], default='D+1', max_length=15),
        ),
    ]
