# Generated by Django 3.2.3 on 2021-11-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20211101_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pamplo',
            name='liquidez',
            field=models.CharField(choices=[('D+1', 'Diária'), ('D+0', 'Imediata'), ('D+30', 'D+30'), ('N', 'Nula'), ('NV', 'No vencimento')], default='D+1', max_length=5),
        ),
migrations.CreateModel(
            name='PCredor',
            fields=[
                ('usuario', models.OneToOneField(on_delete=models.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('liquidez', models.CharField(choices=[('D+1', 'Diária'), ('D+0', 'Imediata'), ('D+30', 'D+30'), ('N', 'Nula'), ('NV', 'No vencimento')], default='D+1', max_length=5)),
                ('aversao_ao_risco', models.CharField(choices=[('A', 'Alta'), ('M', 'Moderada'), ('B', 'Baixa'), ('I', 'Inexistente')], default='I', max_length=15)),
                ('ausencia_impostos', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=15)),
                ('disponibilidade_financeira', models.FloatField(default=30)),
            ],
            options={
                'db_table': 'perfil_c',
            },
        ),
    ]

