# Generated by Django 3.2.3 on 2021-11-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20211101_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pamplo',
            name='disponibilidade_financeira',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='pcredor',
            name='disponibilidade_financeira',
            field=models.FloatField(default=1),
        ),
    ]
